harness:
  account_id: "YOUR_ACCOUNT_ID"  # Get from Account Settings in Harness
  api_key: "YOUR_API_KEY"  # Create in Profile -> My API Keys
  org_id: "default"  # Your organization identifier
  base_url: "https://app.harness.io"

project:
  repo_name: "final-working-project"
  description: "Complete project with all resources using templates"

connectors:
  cluster_connector: "<+input>"
  docker_connector: "<+input>"
  docker_registry_connector: "<+input>"
  docker_registry: "docker.io"
  git_connector: "<+input>"

users:
  developers:
    - dev1@example.com
    - dev2@example.com
  approvers:
    - manager@example.com
  operators:
    - ops@example.com

notifications:
  slack_webhook: "<+input>"
  email_domain: "example.com"

features:
  git_experience: false
  create_rbac: true
  create_pipelines: true

# Template configuration - choose which templates to use
templates:
  nonprod:
    template_ref: "nonprod_deployment_pipeline"  # Template identifier at org level
    version: "v1760729233"  # Latest version with fixes
  prod:
    template_ref: "prod_deployment_pipeline"
    version: "v1760729233"  # Latest version with fixes
